package net.geekhour.problems.p00300.p00389;

import java.util.*;

/**
 * ID: 00389
 * Title: Find the Difference
 * Difficulty: Easy
 * Description: You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde" Output:"e" Explanation: 'e' is the letter that
 * was added.
 *
 * Example 2:
 *
 * Input: s = "", t = "y" Output:"y"
 *
 * Constraints:
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */
class Solution00389 {

  public char findTheDifference(String s, String t) {
    Map<Character, Integer> map = new HashMap<>();
    for (char c : s.toCharArray()) {
      map.put(c, map.getOrDefault(c, 0) + 1);
    }
    for (char c : t.toCharArray()) {
      if (!map.containsKey(c) || map.get(c) == 0) {
        return c;
      }
      map.put(c, map.get(c) - 1);
    }
    return ' ';
  }

  public static void test_00389() {
    Solution00389 solution = new Solution00389();
    System.out.println(solution.findTheDifference("abcd", "abcde"));
    System.out.println(solution.findTheDifference("", "y"));
  }

  public static void main(String[] args) {
    test_00389();
  }
}
